
name: CI

on:
  workflow_dispatch:

jobs:
  data_pipeline:
    runs-on: ubuntu-latest

    steps:

      # Step 1 - Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Show workspace path
      - name: Show workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE

      # Step 3 - Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 4 - Check Python version
      - name: Python version
        run: python --version

      # Step 5 - Install dependencies
      - name: Install dependencies
        run: |
          pip install pandas scikit-learn joblib

      # Step 6 - Clean data
      - name: Clean Data
        run: |
          pwd
          ls -al
          cd ModelCleaning
          python Cleandata.py

      # Step 7 - Train and test model
      - name: Train and Test Model
        run: |
          python ModelCleaning/train_test.py