name: CI
on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Show workspace
        run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
      
      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with: 
              python-version: '3.12'

      - name: python version
        run:
              python -v

  data_pipeline:
    name: data_pipeline
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    - name: Cleandata
      run: |
        pwd
        ls -al
        pwd
        cd ModelCleaning
        pip install pandas
        python Cleandata.py
    - name: train_test
      run: |
        pipinstall scikit-learn jonlib
        python ModelCleaning/train_test.py


